# Generated by Django 5.0.2 on 2024-03-22 09:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trip', models.PositiveIntegerField(default=0, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('expiry_time', models.DateTimeField(null=True)),
                ('today_earning', models.PositiveBigIntegerField(default=0, null=True)),
                ('total_earning', models.PositiveBigIntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Truckpartner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('t_name', models.CharField(max_length=30)),
                ('t_email', models.EmailField(max_length=30, unique=True)),
                ('t_password', models.CharField(max_length=20)),
                ('t_contact', models.CharField(max_length=11, unique=True)),
                ('t_rcnumber', models.CharField(max_length=50, unique=True)),
                ('t_aadharcard_details', models.CharField(max_length=30, unique=True)),
                ('t_pancard_details', models.CharField(max_length=30, unique=True)),
                ('t_drivinglicence_details', models.CharField(max_length=30, unique=True)),
                ('t_picture', models.ImageField(default='images/pic-1.jpg', upload_to='images/')),
                ('package_type', models.CharField(max_length=20, null=True)),
                ('price', models.PositiveIntegerField(null=True)),
                ('razorpay_order_id', models.CharField(blank=True, max_length=100, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=100, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(null=True)),
                ('truck_type', models.CharField(max_length=20, null=True)),
                ('is_online', models.BooleanField(default=False)),
                ('on_work', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=20)),
                ('account_number', models.PositiveIntegerField()),
                ('ifsc_code', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('rides', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.rides')),
                ('truckpartner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner')),
            ],
        ),
        migrations.AddField(
            model_name='rides',
            name='truckpartner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner'),
        ),
    ]
