# Generated by Django 5.0.2 on 2024-03-12 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckpartner',
            name='booking',
        ),
    ]
