# Generated by Django 5.0.2 on 2024-03-14 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_remove_truckpartner_package_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='truck_type',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
