# Generated by Django 5.0.2 on 2024-03-12 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0002_remove_truckpartner_booking'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckpartner',
            name='user',
        ),
    ]
