# Generated by Django 5.0.2 on 2024-03-12 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
        ('myapp2', '0003_remove_truckpartner_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='booking',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.booking'),
        ),
        migrations.AddField(
            model_name='truckpartner',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp.user'),
        ),
    ]
