# Generated by Django 5.0.2 on 2024-03-15 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0003_truckpartner_truck_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='is_online',
            field=models.BooleanField(default=False),
        ),
    ]
