# Generated by Django 5.0.2 on 2024-03-18 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0004_truckpartner_is_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='truckpartner',
            name='on_work',
            field=models.BooleanField(default=False),
        ),
    ]
