# Generated by Django 5.0.2 on 2024-03-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0005_truckpartner_on_work'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='truckpartner',
            name='booking',
        ),
        migrations.RemoveField(
            model_name='truckpartner',
            name='user',
        ),
    ]
