# Generated by Django 5.0.2 on 2024-03-20 05:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0006_remove_truckpartner_booking_remove_truckpartner_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trip', models.PositiveIntegerField(default=0)),
                ('today_earning', models.PositiveBigIntegerField(default=0)),
                ('total_earning', models.PositiveBigIntegerField(default=0)),
                ('truckpartner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner')),
            ],
        ),
    ]
