# Generated by Django 5.0.2 on 2024-03-20 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0007_rides'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Rides',
        ),
    ]
