# Generated by Django 5.0.2 on 2024-03-22 05:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp2', '0008_delete_rides'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rides',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trip', models.PositiveIntegerField(default=0, null=True)),
                ('start_time', models.DateTimeField(null=True)),
                ('expiry_time', models.DateTimeField(null=True)),
                ('today_earning', models.PositiveBigIntegerField(default=0, null=True)),
                ('total_earning', models.PositiveBigIntegerField(default=0, null=True)),
                ('truckpartner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner')),
            ],
        ),
        migrations.CreateModel(
            name='Transactions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_holder_name', models.CharField(max_length=20)),
                ('account_number', models.PositiveIntegerField()),
                ('ifsc_code', models.PositiveIntegerField()),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('amount', models.PositiveBigIntegerField(default=0)),
                ('rides', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.rides')),
                ('truckpartner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='myapp2.truckpartner')),
            ],
        ),
    ]
