# Generated by Django 5.0.2 on 2024-03-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_booking_paid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='zipcode',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
