# Generated by Django 3.0.5 on 2024-02-13 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20240129_1344'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='ucpassword',
        ),
    ]
