# Generated by Django 5.0.2 on 2024-03-07 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_booking_payment_id_booking_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='razorpay_payment_signature',
        ),
    ]
