# Generated by Django 5.0.2 on 2024-03-10 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_alter_booking_zipcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='progress',
            field=models.IntegerField(default=0),
        ),
    ]
