# Generated by Django 5.0.2 on 2024-03-11 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_progress'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='progress',
        ),
        migrations.AddField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[(1, 'PEDDING'), (2, 'DISPATCH'), (3, 'ON THE WAY'), (4, 'DONE')], default=1),
        ),
    ]
