# Generated by Django 5.0.2 on 2024-03-11 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[('house-type', 'house-type'), ('Booking', 'Booking'), (3, 'payment-status'), (4, 'on-the-way'), (5, 'Cancle'), (6, 'finish process')], default=1),
        ),
    ]
