# Generated by Django 5.0.2 on 2024-03-11 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_alter_booking_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='status',
            field=models.IntegerField(choices=[('house-type', 'house-type'), ('Booking', 'Booking'), ('payment-status', 'payment-status'), ('on-the-way', 'on-the-way'), ('cancel', 'Cancle'), ('finish', 'finish process')], default=1),
        ),
    ]
