# Generated by Django 5.0.2 on 2024-03-12 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0014_booking_booking_active_booking_cancel_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='house_type_active',
            field=models.BooleanField(default=True),
        ),
    ]
