# Generated by Django 5.0.2 on 2024-03-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0015_alter_booking_booking_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='booking_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='house_type_active',
            field=models.BooleanField(default=False),
        ),
    ]
